apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sandbox
  region: us-east-2
  version: "1.17"

managedNodeGroups:
  - name: sandbox-managed-ng-1
    instanceType: t2.large
    minSize: 1
    maxSize: 5
    desiredCapacity: 1
    volumeSize: 20
    # ssh:
    #   allow: true
    #   publicKeyPath: ~/.ssh/ec2_id_rsa.pub
    #   # new feature for restricting SSH access to certain AWS security group IDs
    #   sourceSecurityGroupIds: ["sg-00241fbb12c607007"]
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true

fargateProfiles:
  - name: sandbox-fp-default
    selectors:
      # All workloads in the "default" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: fargate
        labels:
          env: sandbox

# Bootstraps kubernetes via Flux CD
git:
  repo:
    url: "git@github.com:robparrott/eks-bootstrap.git"
    branch: sandbox/master
    fluxPath: "flux/"
    user: "gitops"
    email: "rparrott@gmail.com"
  operator:
    namespace: "flux"
    withHelm: true
  # bootstrapProfile:
  #   source: app-dev
  #   revision: master
