apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  releaseName: podinfo
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 7.2.0
    path: airflow
 